### ISSUE TITLE
Json decode error on the buildManifest

### ISSUE THREAD

**Issue by novitae** [0xM1gu3l/NextJSManifestDumper#1]
Replace this:
https://github.com/0xM1gu3l/NextJSManifestDumper/blob/30307723e3e5ed8d4559667c56c6300ea522257b/scripts/getBuildManifest.py#L13-L15

By this:
```py
    build_manifest = driver.execute_script("return JSON.stringify(__BUILD_MANIFEST)")
    driver.close()
    return json.loads(str(build_manifest))
```
Great work G

**Comment by 0xM1gu3l** [comment]
Hey! Thank you for showing me this error! I fixed/tested it and now it should be working fine.

**Comment by novitae** [comment]
@0xM1gu3l Do you have telegram or discord ?

**Comment by 0xM1gu3l** [comment]
> @0xM1gu3l Do you have telegram or discord ?

Yeah, my username is my discord
